title: DENOG e.V.
baseurl: "" # the subpath of your site, e.g. /blog
markdown: kramdown
env: "production"
url: https://bussmannpatrick.github.io/testdenog.github.io/

exclude: ['_theme', package.json, Gemfile, Gemfile.lock, '.idea', '.travis.yml']

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
